version: '2'
services:
  db:
    image: postgres:9.5
    expose:
      - "5432"
    ports:
       - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=teachpass
      - POSTGRES_USER=teach
      - POSTGRES_DB=usersdev

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    volumes: 
      - ./mounted-volume:/mounted-volume
    environment:
      - POSTGRES_PASSWORD=teachpass
      - POSTGRES_USER=teach
      - DB_PORT_5432_TCP_ADDR=db
      - DB_NAME=usersdev
      - DB_USER=teach
      - DB_PASS=teachpass
      - DB_SERVICE=db
      - DB_PORT=5432
    restart: always