- name: Pull down the git repository
  git:
    repo: git@github.com:IrfanFaizullabhoy/teacher.git
    accept_hostkey: True
    dest: /var/www/teacher
    force: yes
    key_file: /home/ubuntu/.ssh/id_rsa
    clone: yes

- name: stop all containers
  shell: docker kill $(docker ps -q)
  ignore_errors: yes

- name: remove all containers
  shell: docker rm $(docker ps -a -q)
  ignore_errors: yes

- name: pull alpine image manually
  shell: docker pull golang:1.7.1-alpine

- name: build teach-bot image manually
  shell: docker build -f /var/www/teacher/server/Dockerfile -t teach-bot /var/www/teacher

- name: run teach-bot image manually
  shell: docker run -d -p 8080:8080 -v mounted-volume:/mounted-volume --name teachbot-api --env-file /var/www/teacher/.env teach-bot

# - name: Run with inline v2 compose
#   docker_service:
#     project_name: teach-bot
#     definition:
#         version: '2'
#         services:
#           server:
#             image: teach-bot
#             ports:
#               - "8080:8080"
#             volumes: 
#               - ./mounted-volume:/mounted-volume
#             env_file: .env